config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates :name, presence: true
    validates :party, presence: true
    validates :age, presence: true
    validates :politics, presence: true


    has_many :vote_logs, dependent: :destroy
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

    before_action :find_candidate_id, only: [:show, :edit, :update, :destroy, :vote]

    def index
        @candidates = Candidate.all
    end

    def show
    end

    def new
        @candidate = Candidate.new
    end

    def create
        @candidate = Candidate.new(candidate_params)

        if @candidate.save
            redirect_to '/candidates', notice: 'Create Candidate successfully!'
            # flash[:notice]='Create Candidate successfully!'
        else
            render :new
        end      
    end

    def edit
    end

    def update
        if @candidate.update(candidate_params)
 
            redirect_to '/candidates', notice: 'Candidate updated successfully!'
        else
            render :edit
        end
    end

    def destroy
        @candidate.destroy

        # flash[:notice]='Candidate deleted and never got back....'
        redirect_to '/candidates', notice: 'Candidate deleted and never got back....'
    end

    def vote
        @candidate.vote_logs.create(ip_address: request.remote_ip)
        
        #send mails
        #VoteMailer.vote_notify('wl02599509@gmail.com').deliver  
        VoteMailJob.perform_later
        # flash[:notice]='Voted!'
        redirect_to '/candidates', notice: 'Voted!'
    end

    private
    def candidate_params
        params.require(:candidate).permit(:name, :party, :age, :politics)
    end

    def find_candidate_id
        @candidate = Candidate.find_by(id: params[:id]) 
    end

    def git_push_test
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>

<%= candidate.errors.full_messages %>

<% end %>


<%= form_for candidate do |form| %>

    <br>
        Name: <%= form.text_field :name %>
    </br>

    <br>
        Party: <%= form.text_field :party %>
    </br>

    <br>
        Age: <%= form.text_field :age %>
    </br>

    <br>
        Politics: <%= form.text_area :politics %>
    </br>

    <br>
        <%= form.submit %>
    </br>

<% end %>

<%= link_to 'back', candidates_path %>

app/views/candidates/edit.html.erb
<h1>Edit Porfile</h1>


<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>VOTE CAMPAIGN</h1>

<%= link_to 'Add Candidate', new_candidate_path %>


<table>
    <tr>
        <td> </td>
        <td> Vote</td>
        <td> Name </td>
        <td> Party </td>
        <td> Age </td>
        <td> Politics </td>
        <td> Action </td>
    </tr>
    
    <% @candidates.each do |candidate| %>
    <tr>
        <td><%= link_to 'Vote', vote_candidate_path(candidate.id), method: 'post' %></td>
        <td><%= candidate.vote_logs.size %></td>
        <td><%= link_to candidate.name, candidate_path(candidate.id) %></td>
        <td><%= candidate.party %></td>
        <td><%= candidate.age %></td>
        <td><%= candidate.politics %></td>
        <td>
            <%= link_to 'edit', edit_candidate_path(candidate.id) %>
            <%= link_to 'delete', candidate_path(candidate.id), method: 'delete', data: {confirm: 'Are you sure?!'} %>
        </td>
    </tr>
    <% end %>
</table>

app/views/candidates/new.html.erb
<H1>Please fulfill the form.</H1>


<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<h1><%= @candidate.name %></h1>


<table>
    <tr>
       <td>Party: <%= @candidate.party %></td>
    </tr>
    <tr>
       <td>Age: <%= @candidate.age %></td>
    </tr>
    <tr>
       <td>Politics: <%= @candidate.politics %></td>
    </tr>
</table>

<%= link_to 'back', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>